### ISSUE TITLE
Bug in the code Line - 7

### ISSUE THREAD

**Issue by yakshithsalian** [yakshithsalian/ProjectGit#1]
Code not accepting from this point.
@bipeensinha , Please take a look.

**Comment by bipeensinha** [comment]
I am working on it

**Comment by yakshithsalian** [comment]
Please keep me posted !

**Comment by bipeensinha** [comment]
<img width="784" alt="avlability zone" src="https://user-images.githubusercontent.com/49720823/143048531-a2bdecbc-a815-4fcd-8406-ac6c852c79a6.png">

**Comment by yakshithsalian** [comment]
Thank you.
Issue resolved. closing it.

**Comment by yakshithsalian** [comment]
Thank you.
Issue resolved. closing it.

**Comment by bipeensinha** [comment]
![devops](https://user-images.githubusercontent.com/49720823/143048851-620415a9-4fdb-47ee-9f0e-46e70aa3df8e.jpg)
